In [1]:
#Дасгал 1
import numpy as np
ls = np.arange(50,100)
ls

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [2]:
#Дасгал 2
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [3]:
# Дасгал2
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
# Дасгал2
np.zeros(10)+6

array([6., 6., 6., 6., 6., 6., 6., 6., 6., 6.])

In [13]:
# Дасгал3
pl = np.arange(20,32)
pk = np.reshape(pl, (3,4), 'C')
print(pk)

[[20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [14]:
# Дасгал4
r = [1,1,1]
ar= np.diag(r)
ar

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [11]:
# Дасгал 5
a = np.arange(1,6)
b = np.diag(x)
b

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [10]:
#Дасгал 6
import numpy as np
f = np.array([[8,15,5,16],[35,85,12,54],[1,2,3,4]])
print(sum(sum(f)))
print(f.sum(axis=0))
print(f.sum(axis=1))

240
[ 44 102  20  74]
[ 44 186  10]


In [28]:
NEYMAR_Salary = [59199687,599199687,62291313,48642850,48874633,49416288,34282846,20538110,13443585,15207527]
RONALDO_Salary = [32498507,32498507,65248182,66470791,66379256,41057823,40332055,33890309,35406722,39862155]
MESSI_Salary = [54000000,66846489,66846489,80834788,83335117,82785363,46677502,45854204,34557919,36113637]
KARIMNEMZEMA_Salary = [19444503,21388953,22458401,22875000,24559380,26243760,1512601,1364204,1620564,1669178]
MBAPPE_Salary = [72000000,7200000,34320405,33765858,20030560,19307286,19307286,1305840,1250480,0]
KANTE_Salary = [18300130,18300130,19749876,20247595,10760170,11006883,3010243,211775,0,0]
SONHEUNGMIN_Salary = [9880000,9880000,7856725,8054587,4938673,5024513,5139717,0,5271178,2492762]
OSCAR_Salary = [17832626,17832627,18995624,20158622,26540100,0,30000000,38199000,40108950,42018900]
DEBRUYNE_Salary = [17632688,17632688,18862876,20093064,21323252,290951,1512601,7317073,7682927,13445120]
KOULIBALY_Salary = [18673000,18673000,15000000,20000000,23200000,0,1512601,1512601,1512601,23300130]
#Matrix
Salary = np.array([NEYMAR_Salary, RONALDO_Salary, MESSI_Salary, KARIMNEMZEMA_Salary, MBAPPE_Salary, KANTE_Salary, SONHEUNGMIN_Salary,OSCAR_Salary, DEBRUYNE_Salary, KOULIBALY_Salary])

#Games 
NEYMAR_G = [708]
RONALDO_G = [900]
MESSI_G = [800]
KARIMNEMZEMA_G = [574]
MBAPPE_G = [454]
KANTE_G = [375]
SONHEUNGMIN_G = [580]
OSCAR_G = [458]
DEBRUYNE_G = [520]
KOULIBALY_G = [560]
Games = np.array([NEYMAR_G, RONALDO_G,MESSI_G,KARIMNEMZEMA_G,MBAPPE_G,KANTE_G, SONHEUNGMIN_G,OSCAR_G, DEBRUYNE_G, KOULIBALY_G])

#Field Goals
NEYMAR_FG = [436]
RONALDO_FG = [700]
MESSI_FG = [750]
KARIMNEMZEMA_FG= [210]
MBAPPE_FG=[200]
KANTE_FG= [110]
SONHEUNGMIN_FG= [210]
OSCAR_FG= [85]
DEBRUYNE_FG= [180]
KOULIBALY_FG= [170]
FIELDGOALS= np.array([NEYMAR_FG,RONALDO_FG,MESSI_FG,KARIMNEMZEMA_FG,MBAPPE_FG,KANTE_FG,SONHEUNGMIN_FG,OSCAR_FG,DEBRUYNE_FG,KOULIBALY_FG])

In [34]:
# 7 Salary mor baganiin niilber
print("Salary COL SUM = ", Salary.sum(axis=0))
print("Salary ROW SUM = ", Salary.sum(axis=1))

Salary COL SUM =  [319461141 809452081 331629891 341143155 329941141 235132867 183287452
 150193116 140854926 174109409]
Salary ROW SUM =  [951096526 453644307 597851508 143136544 208487715 101586802  58538155
 251686449 125793240 123383933]


In [35]:
# 7 Games mor baganiin niilber
print("Games COLUMN SUM = ", Games.sum(axis=0))
print("Games ROW SUM = ", Games.sum(axis=1))

Games COLUMN SUM =  [5929]
Games ROW SUM =  [708 900 800 574 454 375 580 458 520 560]


In [36]:
# 7 FieldGoals mor baganiin niilber
print("FieldGoals COL SUM = ", FIELDGOALS.sum(axis=0))
print("FieldGoals ROW SUM = ", FIELDGOALS.sum(axis=1))

FieldGoals COL SUM =  [3051]
FieldGoals ROW SUM =  [436 700 750 210 200 110 210  85 180 170]
